import React from 'react'
import "./Home.css"


const Home = () => {
  return (

    <>
      <div className="first">
        <div className="imge">
          <img src="/src/assets/image.png" alt="" width={700} height={400} />
        </div>
        <div className="conten">
          <h1>Pawansut Credit Co-Operative</h1>
          <h1>Society Maryadit</h1><br />
          <p>Special schemes for society members of wards 1 to 66 for Gwalior residents.</p>
          <p>First come, first served.</p><br />
          <p >Even if you do not work after joining, there will be no loss. </p>
          <p>You will get discounts on purchasing items and subsidies in the account. </p>
          <p>By working, you will get passive income, convenience income, gift income, </p>
          <p>and on leaving or not leaving work, lifelong pension. </p>
          <p>On death, a large amount will be given to the nominee!</p><br /><br /><br />
          <div className="ms">
            <div className="m">
              <p>Learn, teach, and earnmoney  </p><p>with the freedom of time.</p>
            </div>
          </div>
        </div>
      </div>
      <div className="second">
        <div className="r">
          <h1>Rules Of Society</h1><br />
          <div className="r1">
            <div className="ra">
              1.The subsidy for the month’s purchases will be credited <br />to your bank account on the 5th of every month! <br /><br />

              2.If the discount card balance is empty, topping up with <br />the next charge will be mandatory! <br /><br />

              3.On purchasing essential household items, you will get <br />a discount of 2%–10%, which will be deducted directly <br /> from the bill! <br /><br />

              4.Discount card amount will be valid only for one year <br />from the date of joining. One year later, the discount card <br />amount will automatically expire! <br />
            </div>
            <div className="rb">
              5.Daily closing at 12 PM, Minimum Withdrawal Amount – ₹500/-. <br /><br />

              6.On purchases above ₹2000, home delivery is free within Gwalior <br />city limits! <br /><br />

              7.On continuous monthly purchases between ₹500 and ₹2500 for <br />12 months, one month’s household items will be given free in the <br />13th month! <br /><br />

              8.On referrals, you will get benefits (terms apply). <br /><br />

              9.No maintenance charges! <br />
            </div>
          </div>
          <div className="rc">
            <a href="">Read More</a>
          </div>
        </div>
      </div><br />
      <div className="third">
        <div className="aq">
          <h1>Let us help you choose the <br />best chits plans</h1>
          <a href={"<Contact/>"}><button>Enquire Now</button></a>
        </div>
      </div><br />
      <div className="fifth">
        <h2>Our Strengths</h2>
        <div className="strengths">

          <div className="card">
            <img src="https://img.icons8.com/ios/50/money-bag-rupee.png" alt="Tax Free Dividends" />
            <h3>Tax Free Dividends</h3>
            <div className="corner"></div>
          </div>

          <div className="card">
            <img src="https://img.icons8.com/ios/50/atm.png" alt="Easy Withdrawals" />
            <h3>Easy Withdrawals</h3>
            <div className="corner"></div>
          </div>

          <div className="card">
            <img src="https://img.icons8.com/ios/50/conference.png" alt="Fair Distribution" />
            <h3>Fair Distribution</h3>
            <div className="corner"></div>
          </div>

          <div className="card">
            <img src="https://img.icons8.com/ios/50/hand-cursor.png" alt="Access to Funds" />
            <h3>Access to Funds</h3>
            <div className="corner"></div>
          </div>

          <div className="card">
            <img src="https://img.icons8.com/ios/50/combo-chart.png" alt="Interest Free Payments" />
            <h3>Interest Free Payments</h3>
            <div className="corner"></div>
          </div>

          <div className="card">
            <img src="https://img.icons8.com/ios/50/return.png" alt="Good Returns" />
            <h3>Good Returns</h3>
            <div className="corner"></div>
          </div>

        </div>
      </div><br /><br />
      
      <div className="four">
        <div className="aw">
          <div className="qwer">
            <img src="/src/assets/Screenshot 2025-08-29 122335.png" alt="" width={300} height={400} />
            <h3>Convence Income</h3>
            <p>Passive income is income generated from someone other than an employer or a contractor. It can be generated by earning interest on savings.Aim For Advanced Portfolio Management, Long Term Benefits, Dividend Payout Options & More. 4 Simple Steps To Your Investment With ICICIPruMF. Invest As Low As ₹ 100 Per Month. Expert Fund Managers. Long Term Investment Plan. Paperless Transaction.</p>
            <span><a href="">Read more</a></span>
          </div>
          <div className="qwer">
            <img src="/src/assets/Screenshot 2025-08-29 190715.png" alt="" width={300} height={400} />
            <h3>Festival Income</h3>
            <p>PAWANSUT CREDIT COOPERATIVE & SOCIETY IN A COMPREHENSIVE MUNICIPAL CORPORATION SI MA GWALIOR Co-operative society is registered with the Department of Corporate Affairs as a Societe Pawansut Credit Co-Operative Society firmly established on the principles of co-operative relationship and abides by the Co-operative Relationship Act 1960 Pawansut Credit Co-Operative & Society.</p>
            <span><a href="">Read more</a></span>
          </div>
          <div className="qwer">
            <img src="/src/assets/Screenshot 2025-08-29 191700.png" alt="" width={300} height={400} />
            <h3>Bonus Income</h3>
            <p>PAWANSUT CREDIT COOPERATIVE & SOCIETY IN A COMPREHENSIVE MUNICIPAL CORPORATION SI MA GWALIOR Co-operative society is registered with the Department of Corporate Affairs as a Societe Pawansut Credit Co-Operative Society firmly established on the principles of co-operative relationship and abides by the Co-operative Relationship Act 1960 Pawansut Credit Co-Operative & Society.</p>
            <span><a href="">Read more</a></span>
          </div>
        </div>
      </div><br /><br />
      
      <div className="sixth">
        <div class="container">


          <div class="mission">
            <img src="https://img.icons8.com/ios/50/target.png" alt="Mission Icon" />
            <h2>Our Mission</h2>
            <p>
              To expand our branch network by providing inclusive, secure, and accessible
              financial solutions that mirror our passion to impact each subscriber’s life.
            </p>
          </div>


          <div class="values">
            <h2>Our Values</h2>
            <div class="value-grid">

              <div class="card">
                <img src="https://img.icons8.com/ios/50/like.png" alt="Honesty" />
                <h3>Honesty</h3>
              </div>

              <div class="card">
                <img src="https://img.icons8.com/ios/50/document.png" alt="Compliance" />
                <h3>Compliance</h3>
              </div>

              <div class="card">
                <img src="https://img.icons8.com/ios/50/conference.png" alt="Employee Empathy" />
                <h3>Employee Empathy</h3>
              </div>

              <div class="card">
                <img src="https://img.icons8.com/ios/50/shield.png" alt="Best Practices" />
                <h3>Best in Class Practices</h3>
              </div>

              <div class="card">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="blue" class="bi bi-people-fill" viewBox="0 0 16 16">
                  <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5" />
                </svg>
                <h3>Subscriber Focus</h3>
              </div>

              <div class="card">
                <img src="https://img.icons8.com/ios/50/scales.png" alt="Integrity" />
                <h3>Integrity</h3>
              </div>

            </div>
          </div>

        </div>
      </div>
      
    </>

  )
}

export default Home